# Generated by Django 3.1.7 on 2021-11-13 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField(verbose_name='Matricule')),
                ('image', models.ImageField(default='static/default_image.jpg', upload_to='static/images', verbose_name='Image')),
                ('marque', models.CharField(max_length=20, verbose_name='Marque')),
                ('modele', models.CharField(max_length=20, verbose_name='Modele')),
                ('annee', models.IntegerField(verbose_name='Annee')),
                ('nbrPersonne', models.IntegerField(verbose_name='Nombre de Personnes')),
                ('nbrPortes', models.IntegerField(verbose_name='Nombre de Portes')),
                ('carburant', models.CharField(choices=[('Diesel', 'Diesel'), ('Essence', 'Essence')], max_length=20, verbose_name='Carburant')),
                ('transmission', models.CharField(choices=[('Automatique', 'Automatique'), ('Manuelle', 'Manuelle')], max_length=20, verbose_name='Transmission')),
                ('couleur', models.CharField(max_length=20, verbose_name='Couleur')),
                ('consommation', models.IntegerField(verbose_name='Consommation KM/L')),
                ('gps', models.BooleanField(default=True, verbose_name='GPS Availability')),
                ('prix', models.IntegerField(verbose_name='Prix par jour')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
            ],
            options={
                'verbose_name': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=10, verbose_name='CIN')),
                ('tel', models.CharField(max_length=10, verbose_name='Telephone')),
                ('dateN', models.DateField(auto_now_add=True, verbose_name='Date de naissance')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
    ]
