# Generated by Django 3.1.7 on 2021-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_auto_20211120_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Prix Total'),
        ),
    ]
