# Generated by Django 3.1.7 on 2021-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateD',
            field=models.DateField(verbose_name='Pick-Up'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateF',
            field=models.DateField(verbose_name='Drop-Off'),
        ),
    ]
