# Generated by Django 3.1.7 on 2021-12-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_auto_20211214_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marque',
            options={'verbose_name': 'Marque'},
        ),
    ]
